# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - jupyter-book clean reliablemlbook/
      - jupyter-book build reliablemlbook/
    silent: false
  pdf:
    cmds:
      - jupyter-book clean reliablemlbook/
      - jupyter-book build reliablemlbook/ --builder pdflatex
      - cp reliablemlbook/_build/latex/book.pdf .
    silent: false
